-- Airline reference-data refresh (generated by prisma/seed-data/generate-airline-migration.ts from
-- prisma/seed-data/airlines-curated.json — edit that file and regenerate, never this one).
--
-- WHY: the bundled OpenFlights airline data is years old. Many airlines that operate today could not be found because
-- their IATA code was still held by a defunct airline that was later given the code again (Pegasus PC, Volotea V7,
-- SpiceJet SG, Jazeera J9, Starlux JX, Air Premia YP, Azul AD, Viva Aerobus VB, VietJet VJ ...), and ~75 carriers that
-- ceased long ago were still flagged active. Every entry below carries an IATA + ICAO pair that was cross-checked
-- against two independent sources (see the JSON).
--
-- SAFETY: nothing is deleted and no foreign key is touched. A recycled code is FREED from its previous holder, which keeps
-- its row, id, name and ICAO (marked inactive), so every existing FlightSegment still points at the airline it was saved
-- with. Where the holder is the same company renamed (Brussels Airlines, Norwegian, Envoy, Endeavor ...) the row is
-- relabelled in place. The script is idempotent (a second run changes nothing) and each airline is applied in its own
-- sub-transaction, so one unexpected row can never abort the rest or block a deploy.

DO $$
DECLARE
  r RECORD;
  h RECORD;
  own_id integer;
BEGIN
  -- 1. Placeholder IATA values in the old data ('--', '??', '8z', ...) are not designators: clear them.
  FOR r IN SELECT id FROM "Airline" WHERE iata IS NOT NULL AND iata !~ '^[A-Z0-9]{2}$' LOOP
    BEGIN
      UPDATE "Airline" SET iata = NULL WHERE id = r.id;
    EXCEPTION WHEN unique_violation THEN
      UPDATE "Airline" SET iata = NULL, icao = NULL WHERE id = r.id;
    END;
  END LOOP;

  -- 1b. Likewise ICAO values that are not three letters (placeholders such as 'BA1', '000'): clear them.
  UPDATE "Airline" SET icao = NULL WHERE icao IS NOT NULL AND icao !~ '^[A-Z]{3}$';

  -- 2. Curated corrections and additions.
  FOR r IN SELECT * FROM (VALUES
    ('EC'::text, 'EJU'::text, 'easyJet Europe'::text, 'Austria'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('BY'::text, 'TOM'::text, 'TUI Airways'::text, 'United Kingdom'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('TB'::text, 'JAF'::text, 'TUI fly Belgium'::text, 'Belgium'::text, true, 'relabel'::text, true, NULL::text, NULL::text, NULL::text),
    ('X3'::text, 'TUI'::text, 'TUIfly'::text, 'Germany'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('OR'::text, 'TFL'::text, 'TUI fly Netherlands'::text, 'Netherlands'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('LM'::text, 'LOG'::text, 'Loganair'::text, 'United Kingdom'::text, true, 'adopt'::text, false, 'Logan Air'::text, 'LOG'::text, NULL::text),
    ('RK'::text, 'RUK'::text, 'Ryanair UK'::text, 'United Kingdom'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('SN'::text, 'BEL'::text, 'Brussels Airlines'::text, 'Belgium'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('4Y'::text, 'OCN'::text, 'Discover Airlines'::text, 'Germany'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('WK'::text, 'EDW'::text, 'Edelweiss Air'::text, 'Switzerland'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('TO'::text, 'TVF'::text, 'Transavia France'::text, 'France'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('SS'::text, 'CRL'::text, 'Corsair International'::text, 'France'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('BF'::text, 'FBU'::text, 'French Bee'::text, 'France'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('VY'::text, 'VLG'::text, 'Vueling'::text, 'Spain'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('V7'::text, 'VOE'::text, 'Volotea'::text, 'Spain'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('TP'::text, 'TAP'::text, 'TAP Air Portugal'::text, 'Portugal'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('S4'::text, 'RZO'::text, 'SATA Azores Airlines'::text, 'Portugal'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('AZ'::text, 'ITY'::text, 'ITA Airways'::text, 'Italy'::text, true, 'relabel'::text, true, NULL::text, NULL::text, NULL::text),
    ('NO'::text, 'NOS'::text, 'Neos'::text, 'Italy'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('GQ'::text, 'SEH'::text, 'Sky Express'::text, 'Greece'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('QS'::text, 'TVS'::text, 'Smartwings'::text, 'Czech Republic'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('JU'::text, 'ASL'::text, 'Air Serbia'::text, 'Serbia'::text, true, 'relabel'::text, true, NULL::text, NULL::text, NULL::text),
    ('ZB'::text, 'ABN'::text, 'Air Albania'::text, 'Albania'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('DY'::text, 'NOZ'::text, 'Norwegian Air Shuttle'::text, 'Norway'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('N0'::text, 'NBT'::text, 'Norse Atlantic Airways'::text, 'Norway'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('PC'::text, 'PGT'::text, 'Pegasus Airlines'::text, 'Turkey'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('VF'::text, 'TKJ'::text, 'AJet'::text, 'Turkey'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('XC'::text, 'CAI'::text, 'Corendon Airlines'::text, 'Turkey'::text, true, 'adopt'::text, false, 'Corendon Airlines'::text, 'CAI'::text, NULL::text),
    ('DP'::text, 'PBD'::text, 'Pobeda'::text, 'Russia'::text, true, 'adopt'::text, false, 'Pobeda'::text, 'PBD'::text, NULL::text),
    ('PS'::text, 'AUI'::text, 'Ukraine International Airlines'::text, 'Ukraine'::text, false, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('DV'::text, 'VSV'::text, 'SCAT Airlines'::text, 'Kazakhstan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('XY'::text, 'KNE'::text, 'flynas'::text, 'Saudi Arabia'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('F3'::text, 'FAD'::text, 'flyadeal'::text, 'Saudi Arabia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('RX'::text, 'RXI'::text, 'Riyadh Air'::text, 'Saudi Arabia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('GF'::text, 'GFA'::text, 'Gulf Air'::text, 'Bahrain'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('J9'::text, 'JZR'::text, 'Jazeera Airways'::text, 'Kuwait'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('OV'::text, 'OMS'::text, 'SalamAir'::text, 'Oman'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('IZ'::text, 'AIZ'::text, 'Arkia Israeli Airlines'::text, 'Israel'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('RB'::text, 'SYR'::text, 'Syrian Air'::text, 'Syria'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('TR'::text, 'TGW'::text, 'Scoot'::text, 'Singapore'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('HB'::text, 'HGB'::text, 'Greater Bay Airlines'::text, 'Hong Kong'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('9C'::text, 'CQH'::text, 'Spring Airlines'::text, 'China'::text, true, 'adopt'::text, false, 'Spring Airlines'::text, 'CQH'::text, '9S'::text),
    ('HO'::text, 'DKH'::text, 'Juneyao Air'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('GS'::text, 'GCR'::text, 'Tianjin Airlines'::text, 'China'::text, true, 'adopt'::text, false, 'Tianjin Airlines'::text, 'GCR'::text, NULL::text),
    ('8L'::text, 'LKE'::text, 'Lucky Air'::text, 'China'::text, true, 'adopt'::text, false, 'Lucky Air'::text, 'LKE'::text, NULL::text),
    ('GJ'::text, 'CDC'::text, 'Loong Air'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('BK'::text, 'OKA'::text, 'Okay Airways'::text, 'China'::text, true, 'adopt'::text, false, 'Okay Airways'::text, 'OKA'::text, NULL::text),
    ('JD'::text, 'CBJ'::text, 'Beijing Capital Airlines'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('G5'::text, 'HXA'::text, 'China Express Airlines'::text, 'China'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('TV'::text, 'TBA'::text, 'Tibet Airlines'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('KN'::text, 'CUA'::text, 'China United Airlines'::text, 'China'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('JX'::text, 'SJX'::text, 'Starlux Airlines'::text, 'Taiwan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('IT'::text, 'TTW'::text, 'Tigerair Taiwan'::text, 'Taiwan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('MM'::text, 'APJ'::text, 'Peach Aviation'::text, 'Japan'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('ZG'::text, 'TZP'::text, 'ZIPAIR Tokyo'::text, 'Japan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('6J'::text, 'SNJ'::text, 'Solaseed Air'::text, 'Japan'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('HD'::text, 'ADO'::text, 'Air Do'::text, 'Japan'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('GK'::text, 'JJP'::text, 'Jetstar Japan'::text, 'Japan'::text, true, 'adopt'::text, false, 'Jetstar Japan'::text, 'JJP'::text, NULL::text),
    ('IJ'::text, 'SJO'::text, 'Spring Airlines Japan'::text, 'Japan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('LJ'::text, 'JNA'::text, 'Jin Air'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('TW'::text, 'TWB'::text, 'T''way Air'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('BX'::text, 'ABL'::text, 'Air Busan'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('RS'::text, 'ASV'::text, 'Air Seoul'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('ZE'::text, 'ESR'::text, 'Eastar Jet'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('YP'::text, 'APZ'::text, 'Air Premia'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('RF'::text, 'EOK'::text, 'Aero K'::text, 'South Korea'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('SL'::text, 'TLM'::text, 'Thai Lion Air'::text, 'Thailand'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('VZ'::text, 'TVJ'::text, 'Thai VietJet Air'::text, 'Thailand'::text, true, 'adopt'::text, false, 'Thai Vietjet Air'::text, 'TVJ'::text, NULL::text),
    ('VJ'::text, 'VJC'::text, 'VietJet Air'::text, 'Vietnam'::text, true, 'adopt'::text, false, 'VietJet Air'::text, 'VJC'::text, NULL::text),
    ('QH'::text, 'BAV'::text, 'Bamboo Airways'::text, 'Vietnam'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('VU'::text, 'VAG'::text, 'Vietravel Airlines'::text, 'Vietnam'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('BL'::text, 'PIC'::text, 'Pacific Airlines'::text, 'Vietnam'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('2P'::text, 'GAP'::text, 'PAL Express'::text, 'Philippines'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('Z2'::text, 'APG'::text, 'AirAsia Philippines'::text, 'Philippines'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('D7'::text, 'XAX'::text, 'AirAsia X'::text, 'Malaysia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('OD'::text, 'MXD'::text, 'Batik Air Malaysia'::text, 'Malaysia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('JT'::text, 'LNI'::text, 'Lion Air'::text, 'Indonesia'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('ID'::text, 'BTK'::text, 'Batik Air'::text, 'Indonesia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('QG'::text, 'CTV'::text, 'Citilink'::text, 'Indonesia'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('IU'::text, 'SJV'::text, 'Super Air Jet'::text, 'Indonesia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('K6'::text, 'KHV'::text, 'Cambodia Angkor Air'::text, 'Cambodia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('UB'::text, 'UBA'::text, 'Myanmar National Airlines'::text, 'Myanmar'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('SG'::text, 'SEJ'::text, 'SpiceJet'::text, 'India'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('QP'::text, 'AKJ'::text, 'Akasa Air'::text, 'India'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('9I'::text, 'LLR'::text, 'Alliance Air'::text, 'India'::text, true, 'adopt'::text, false, 'Alliance Air'::text, 'LLR'::text, 'CD'::text),
    ('S5'::text, 'SDG'::text, 'Star Air'::text, 'India'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('BS'::text, 'UBG'::text, 'US-Bangla Airlines'::text, 'Bangladesh'::text, true, 'adopt'::text, false, 'US-Bangla Airlines'::text, 'UBG'::text, NULL::text),
    ('VQ'::text, 'NVQ'::text, 'Novoair'::text, 'Bangladesh'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('U4'::text, 'BHA'::text, 'Buddha Air'::text, 'Nepal'::text, true, 'adopt'::text, false, 'Buddha Air'::text, 'BHA'::text, NULL::text),
    ('YT'::text, 'NYT'::text, 'Yeti Airlines'::text, 'Nepal'::text, true, 'adopt'::text, false, 'Yeti Airlines'::text, 'NYT'::text, NULL::text),
    ('H9'::text, 'HIM'::text, 'Himalaya Airlines'::text, 'Nepal'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('PA'::text, 'ABQ'::text, 'Airblue'::text, 'Pakistan'::text, true, 'adopt'::text, false, 'Airblue'::text, 'ABQ'::text, 'ED'::text),
    ('PF'::text, 'SIF'::text, 'AirSial'::text, 'Pakistan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('9P'::text, 'FJL'::text, 'Fly Jinnah'::text, 'Pakistan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('Q2'::text, 'DQA'::text, 'Maldivian'::text, 'Maldives'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('NR'::text, 'MAV'::text, 'Manta Air'::text, 'Maldives'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('VA'::text, 'VOZ'::text, 'Virgin Australia'::text, 'Australia'::text, true, 'relabel'::text, true, NULL::text, NULL::text, NULL::text),
    ('FJ'::text, 'FJI'::text, 'Fiji Airways'::text, 'Fiji'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('SB'::text, 'ACI'::text, 'Aircalin'::text, 'New Caledonia'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('F8'::text, 'FLE'::text, 'Flair Airlines'::text, 'Canada'::text, true, 'adopt'::text, false, 'Flair Airlines'::text, 'FLE'::text, NULL::text),
    ('MX'::text, 'MXY'::text, 'Breeze Airways'::text, 'United States'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('XP'::text, 'VXP'::text, 'Avelo Airlines'::text, 'United States'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('9X'::text, 'SOU'::text, 'Southern Airways Express'::text, 'United States'::text, true, 'adopt'::text, false, 'Southern Airways'::text, 'SOU'::text, NULL::text),
    ('YX'::text, 'RPA'::text, 'Republic Airways'::text, 'United States'::text, true, 'adopt'::text, false, 'Republic Airlines'::text, 'RPA'::text, 'RW'::text),
    ('MQ'::text, 'ENY'::text, 'Envoy Air'::text, 'United States'::text, true, 'relabel'::text, true, NULL::text, NULL::text, NULL::text),
    ('OH'::text, 'JIA'::text, 'PSA Airlines'::text, 'United States'::text, true, 'adopt'::text, false, 'PSA Airlines'::text, 'JIA'::text, NULL::text),
    ('9E'::text, 'EDV'::text, 'Endeavor Air'::text, 'United States'::text, true, 'relabel'::text, true, NULL::text, NULL::text, NULL::text),
    ('G7'::text, 'GJS'::text, 'GoJet Airlines'::text, 'United States'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('C5'::text, 'UCA'::text, 'CommuteAir'::text, 'United States'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('VB'::text, 'VIV'::text, 'Viva Aerobus'::text, 'Mexico'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('LA'::text, 'LAN'::text, 'LATAM Airlines'::text, 'Chile'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('JJ'::text, 'TAM'::text, 'LATAM Airlines Brasil'::text, 'Brazil'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('G3'::text, 'GLO'::text, 'GOL Linhas Aereas'::text, 'Brazil'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('AD'::text, 'AZU'::text, 'Azul Brazilian Airlines'::text, 'Brazil'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('FO'::text, 'FBZ'::text, 'Flybondi'::text, 'Argentina'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('JA'::text, 'JAT'::text, 'JetSMART'::text, 'Chile'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('WJ'::text, 'JES'::text, 'JetSMART Argentina'::text, 'Argentina'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('P5'::text, 'RPB'::text, 'Wingo'::text, 'Colombia'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('DM'::text, 'DWI'::text, 'Arajet'::text, 'Dominican Republic'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('OB'::text, 'BOV'::text, 'Boliviana de Aviación'::text, 'Bolivia'::text, true, 'adopt'::text, false, 'Boliviana de Aviacion (OB)'::text, 'BOV'::text, NULL::text),
    ('JY'::text, 'IWY'::text, 'interCaribbean Airways'::text, 'Turks and Caicos Islands'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('SM'::text, 'MSC'::text, 'Air Cairo'::text, 'Egypt'::text, true, 'adopt'::text, false, 'Air Cairo'::text, 'MSC'::text, NULL::text),
    ('4Z'::text, 'LNK'::text, 'Airlink'::text, 'South Africa'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('FA'::text, 'SFR'::text, 'Safair'::text, 'South Africa'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('HC'::text, 'SZN'::text, 'Air Senegal'::text, 'Senegal'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('KP'::text, 'SKK'::text, 'ASKY Airlines'::text, 'Togo'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('HF'::text, 'VRE'::text, 'Air Côte d''Ivoire'::text, 'Cote d''Ivoire'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('P4'::text, 'APK'::text, 'Air Peace'::text, 'Nigeria'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('UR'::text, 'UGD'::text, 'Uganda Airlines'::text, 'Uganda'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('TM'::text, 'LAM'::text, 'LAM Mozambique Airlines'::text, 'Mozambique'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('A2'::text, 'AZI'::text, 'Astra Airlines'::text, 'Greece'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('AP'::text, 'LAV'::text, 'AlbaStar'::text, 'Spain'::text, true, 'adopt'::text, false, 'AlbaStar'::text, 'LAV'::text, NULL::text),
    ('AW'::text, 'AFW'::text, 'Africa World Airlines'::text, 'Ghana'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('E4'::text, 'ENT'::text, 'Enter Air'::text, 'Poland'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('FH'::text, 'FHY'::text, 'Freebird Airlines'::text, 'Turkey'::text, true, 'adopt'::text, false, 'Free Bird Airlines'::text, 'FHY'::text, NULL::text),
    ('E5'::text, 'RBG'::text, 'Air Arabia Egypt'::text, 'Egypt'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('3O'::text, 'MAC'::text, 'Air Arabia Maroc'::text, 'Morocco'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('3L'::text, 'ADY'::text, 'Air Arabia Abu Dhabi'::text, 'United Arab Emirates'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('CJ'::text, 'CFE'::text, 'BA CityFlyer'::text, 'United Kingdom'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('QC'::text, 'CRC'::text, 'Camair-Co'::text, 'Cameroon'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('C7'::text, 'CIN'::text, 'Cinnamon Air'::text, 'Sri Lanka'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('CD'::text, 'CND'::text, 'Corendon Dutch Airlines'::text, 'Netherlands'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('F6'::text, 'VAW'::text, 'Fly2Sky'::text, 'Bulgaria'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('5F'::text, 'FIA'::text, 'FlyOne'::text, 'Moldova'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('H4'::text, 'HYS'::text, 'HiSky'::text, 'Romania'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('HJ'::text, 'USW'::text, 'HumoAir'::text, 'Uzbekistan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('K9'::text, 'TEZ'::text, 'TezJet'::text, 'Kyrgyzstan'::text, true, 'adopt'::text, false, 'Tez Jet Airlines'::text, 'TEZ'::text, NULL::text),
    ('TI'::text, 'TWI'::text, 'Tailwind Airlines'::text, 'Turkey'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('PQ'::text, 'SQP'::text, 'SkyUp Airlines'::text, 'Ukraine'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('N4'::text, 'NWS'::text, 'Nordwind Airlines'::text, 'Russia'::text, true, 'adopt'::text, false, 'NordWind Airlines'::text, 'NWS'::text, NULL::text),
    ('MR'::text, 'MML'::text, 'Hunnu Air'::text, 'Mongolia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('3H'::text, 'AIE'::text, 'Air Inuit'::text, 'Canada'::text, true, 'adopt'::text, false, 'Air Inuit'::text, 'AIE'::text, NULL::text),
    ('YN'::text, 'CRQ'::text, 'Air Creebec'::text, 'Canada'::text, true, 'adopt'::text, false, 'Air Creebec'::text, 'CRQ'::text, NULL::text),
    ('9M'::text, 'GLR'::text, 'Central Mountain Air'::text, 'Canada'::text, true, 'adopt'::text, false, 'Central Mountain Air'::text, 'GLR'::text, NULL::text),
    ('WT'::text, 'WSG'::text, 'Wasaya Airways'::text, 'Canada'::text, true, 'adopt'::text, false, 'Wasaya Airways'::text, 'WSG'::text, NULL::text),
    ('PB'::text, 'PVL'::text, 'PAL Airlines'::text, 'Canada'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('P6'::text, 'PSC'::text, 'Pascan Aviation'::text, 'Canada'::text, true, 'adopt'::text, false, 'Pascan Aviation'::text, 'PSC'::text, NULL::text),
    ('QK'::text, 'JZA'::text, 'Jazz Aviation'::text, 'Canada'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('WR'::text, 'WEN'::text, 'WestJet Encore'::text, 'Canada'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('LF'::text, 'VTE'::text, 'Contour Airlines'::text, 'United States'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('5R'::text, 'RUC'::text, 'Rutaca'::text, 'Venezuela'::text, true, 'adopt'::text, false, 'Rutas Aereas'::text, 'RUC'::text, NULL::text),
    ('QL'::text, 'LER'::text, 'Laser Airlines'::text, 'Venezuela'::text, true, 'adopt'::text, false, 'Linea Aerea de Servicio Ejecutivo Regional'::text, 'LER'::text, '8z'::text),
    ('9R'::text, 'NSE'::text, 'Satena'::text, 'Colombia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('VE'::text, 'EFY'::text, 'EasyFly'::text, 'Colombia'::text, true, 'adopt'::text, false, 'EasyFly'::text, 'EFY'::text, NULL::text),
    ('LP'::text, 'LPE'::text, 'LATAM Airlines Peru'::text, 'Peru'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('4C'::text, 'ARE'::text, 'LATAM Airlines Colombia'::text, 'Colombia'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('XL'::text, 'LNE'::text, 'LATAM Airlines Ecuador'::text, 'Ecuador'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('5D'::text, 'SLI'::text, 'Aeromexico Connect'::text, 'Mexico'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('YQ'::text, 'LCT'::text, 'TAR Aerolineas'::text, 'Mexico'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('Q9'::text, 'WAN'::text, 'Wataniya Airways'::text, 'Kuwait'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('IF'::text, 'FBA'::text, 'Fly Baghdad'::text, 'Iraq'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('QB'::text, 'QSM'::text, 'Qeshm Air'::text, 'Iran'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('B9'::text, 'IRB'::text, 'Iran Airtour'::text, 'Iran'::text, true, 'adopt'::text, false, 'Iranair Tours'::text, 'IRB'::text, NULL::text),
    ('JM'::text, 'JMA'::text, 'Jambojet'::text, 'Kenya'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('5Z'::text, 'KEM'::text, 'CemAir'::text, 'South Africa'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('LN'::text, 'LAA'::text, 'Libyan Airlines'::text, 'Libya'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('OF'::text, 'OLA'::text, 'Overland Airways'::text, 'Nigeria'::text, true, 'adopt'::text, false, 'Overland Airways'::text, 'OLA'::text, 'OJ'::text),
    ('W3'::text, 'ARA'::text, 'Arik Air'::text, 'Nigeria'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('SZ'::text, 'SMR'::text, 'Somon Air'::text, 'Tajikistan'::text, true, 'adopt'::text, false, 'Somon Air'::text, 'SMR'::text, NULL::text),
    ('7J'::text, 'TJK'::text, 'Tajik Air'::text, 'Tajikistan'::text, true, 'relabel'::text, false, NULL::text, NULL::text, NULL::text),
    ('XJ'::text, 'TAX'::text, 'Thai AirAsia X'::text, 'Thailand'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('NS'::text, 'HBH'::text, 'Hebei Airlines'::text, 'China'::text, true, 'adopt'::text, false, 'Hebei Airlines'::text, 'HBH'::text, NULL::text),
    ('QW'::text, 'QDA'::text, 'Qingdao Airlines'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('EU'::text, 'UEA'::text, 'Chengdu Airlines'::text, 'China'::text, true, 'adopt'::text, false, 'United Eagle Airlines'::text, 'UEA'::text, NULL::text),
    ('FU'::text, 'FZA'::text, 'Fuzhou Airlines'::text, 'China'::text, true, 'adopt'::text, false, 'Fuzhou Airlines'::text, 'FZA'::text, NULL::text),
    ('KY'::text, 'KNA'::text, 'Kunming Airlines'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('GY'::text, 'CGZ'::text, 'Colorful Guizhou Airlines'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('DZ'::text, 'EPA'::text, 'Donghai Airlines'::text, 'China'::text, true, 'adopt'::text, false, 'Shenzhen Donghai Airlines'::text, 'EPA'::text, NULL::text),
    ('JR'::text, 'JOY'::text, 'Joy Air'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('UQ'::text, 'CUH'::text, 'Urumqi Air'::text, 'China'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('9H'::text, 'CGN'::text, 'Air Changan'::text, 'China'::text, true, 'adopt'::text, false, 'Changan Airlines'::text, 'CGN'::text, '2Z'::text),
    ('XK'::text, 'CCM'::text, 'Air Corsica'::text, 'France'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('PM'::text, 'CNF'::text, 'Canaryfly'::text, 'Spain'::text, true, 'adopt'::text, false, 'Canaryfly'::text, 'CNF'::text, NULL::text),
    ('SR'::text, 'SDR'::text, 'Sundair'::text, 'Germany'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('P9'::text, 'PVN'::text, 'Peruvian Airlines'::text, 'Peru'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('5K'::text, 'HFY'::text, 'Hi Fly'::text, 'Portugal'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('ZT'::text, 'AWC'::text, 'Titan Airways'::text, 'United Kingdom'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('SF'::text, 'DTH'::text, 'Tassili Airlines'::text, 'Algeria'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('SX'::text, 'SRK'::text, 'Sky Work Airlines'::text, 'Switzerland'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('JH'::text, 'FDA'::text, 'Fuji Dream Airlines'::text, 'Japan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('OC'::text, 'ORC'::text, 'Oriental Air Bridge'::text, 'Japan'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('3X'::text, 'JAC'::text, 'Japan Air Commuter'::text, 'Japan'::text, true, 'adopt'::text, false, 'Japan Air Commuter'::text, 'JAC'::text, NULL::text),
    ('EH'::text, 'AKX'::text, 'ANA Wings'::text, 'Japan'::text, true, 'update'::text, false, NULL::text, NULL::text, NULL::text),
    ('0V'::text, 'VFC'::text, 'Vietnam Air Services Company'::text, 'Vietnam'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('ZA'::text, 'SWM'::text, 'Sky Angkor Airlines'::text, 'Cambodia'::text, true, 'adopt'::text, false, 'Sky Angkor Airlines (ZA)'::text, 'SWM'::text, NULL::text),
    ('8M'::text, 'MMA'::text, 'Myanmar Airways International'::text, 'Myanmar'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('7Y'::text, 'MYP'::text, 'Mann Yadanarpon Airlines'::text, 'Myanmar'::text, true, 'adopt'::text, false, 'Mann Yadanarpon Airlines'::text, 'MYP'::text, NULL::text),
    ('IW'::text, 'WON'::text, 'Wings Air'::text, 'Indonesia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('8B'::text, 'TNU'::text, 'TransNusa'::text, 'Indonesia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('IN'::text, 'LKN'::text, 'NAM Air'::text, 'Indonesia'::text, true, 'insert'::text, false, NULL::text, NULL::text, NULL::text),
    ('IP'::text, 'PAS'::text, 'Pelita Air'::text, 'Indonesia'::text, true, 'adopt'::text, false, 'Pelita Air Service'::text, 'PAS'::text, NULL::text)
  ) AS t(iata, icao, name, country, is_active, mode, keep_previous, own_name, own_icao, own_iata)
  LOOP
    BEGIN
      SELECT id, name, icao, country INTO h FROM "Airline" WHERE iata = r.iata;

      -- The row holding this IATA already is this airline.
      IF h.id IS NOT NULL AND h.icao IS NOT DISTINCT FROM r.icao THEN
        UPDATE "Airline" SET name = r.name, "isActive" = r.is_active, country = COALESCE(country, r.country) WHERE id = h.id;
        CONTINUE;
      END IF;

      -- Same company renamed / successor on the same code: relabel in place, keep the previous identity if it differs.
      IF r.mode = 'relabel' AND h.id IS NOT NULL THEN
        IF r.keep_previous AND h.icao IS NOT NULL THEN
          INSERT INTO "Airline" (iata, icao, name, country, "isActive") VALUES (NULL, h.icao, h.name, h.country, false) ON CONFLICT DO NOTHING;
        END IF;
        UPDATE "Airline" SET name = r.name, icao = r.icao, "isActive" = r.is_active, country = COALESCE(country, r.country) WHERE id = h.id;
        CONTINUE;
      END IF;

      -- Recycled code: free it from the previous holder (kept as an inactive, code-less record).
      IF h.id IS NOT NULL THEN
        BEGIN
          UPDATE "Airline" SET iata = NULL, "isActive" = false, "logoUrl" = NULL WHERE id = h.id;
        EXCEPTION WHEN unique_violation THEN
          UPDATE "Airline" SET iata = NULL, icao = NULL, "isActive" = false, "logoUrl" = NULL WHERE id = h.id;
        END;
      END IF;

      -- The airline's own existing row (listed without, or under a wrong, IATA code) gains the code; otherwise add it.
      own_id := NULL;
      IF r.own_name IS NOT NULL THEN
        SELECT id INTO own_id FROM "Airline"
         WHERE name = r.own_name AND icao IS NOT DISTINCT FROM r.own_icao AND (iata IS NULL OR iata IS NOT DISTINCT FROM r.own_iata)
         ORDER BY id LIMIT 1;
      END IF;
      IF own_id IS NOT NULL THEN
        UPDATE "Airline" SET iata = r.iata, icao = r.icao, name = r.name, country = COALESCE(country, r.country), "isActive" = r.is_active, "logoUrl" = NULL WHERE id = own_id;
      ELSE
        INSERT INTO "Airline" (iata, icao, name, country, "isActive") VALUES (r.iata, r.icao, r.name, r.country, r.is_active) ON CONFLICT DO NOTHING;
      END IF;
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'airline refresh skipped % (%): %', r.iata, r.name, SQLERRM;
    END;
  END LOOP;

  -- 3. Airlines that ceased operating but were still flagged active. Only the flag changes — never a delete.
  UPDATE "Airline" a SET "isActive" = false
    FROM (VALUES
    ('AN'::text, 'AAA'::text, 'Ansett Australia'::text),
    ('AQ'::text, 'AAH'::text, 'Aloha Airlines'::text),
    ('JP'::text, 'ADR'::text, 'Adria Airways'::text),
    ('PE'::text, 'AEL'::text, 'Air Europe'::text),
    ('5W'::text, 'AEU'::text, 'Astraeus'::text),
    ('VV'::text, 'AEW'::text, 'Aerosvit Airlines'::text),
    ('SW'::text, 'NMB'::text, 'Air Namibia'::text),
    ('PL'::text, 'PLI'::text, 'Aeroper'::text),
    ('8A'::text, 'BMM'::text, 'Atlas Blue'::text),
    ('AB'::text, 'BER'::text, 'Air Berlin'::text),
    ('GV'::text, 'ARF'::text, 'Aero Flight'::text),
    ('JW'::text, 'APW'::text, 'Arrow Air'::text),
    ('IQ'::text, 'AUB'::text, 'Augsburg Airways'::text),
    ('6G'::text, 'AWW'::text, 'Air Wales'::text),
    ('XT'::text, 'AXL'::text, 'Air Exel'::text),
    ('3G'::text, 'AYZ'::text, 'Atlant-Soyuz Airlines'::text),
    ('NM'::text, 'DRD'::text, 'Air Madrid'::text),
    ('TD'::text, 'LUR'::text, 'Atlantis European Airways'::text),
    ('U8'::text, 'RNV'::text, 'Armavia'::text),
    ('FL'::text, 'TRS'::text, 'AirTran Airways'::text),
    ('BD'::text, 'BMA'::text, 'bmi'::text),
    ('WW'::text, 'BMI'::text, 'bmibaby'::text),
    ('KJ'::text, 'LAJ'::text, 'British Mediterranean Airways'::text),
    ('CP'::text, 'CDN'::text, 'Canadian Airlines'::text),
    ('3Q'::text, 'CYH'::text, 'Yunnan Airlines'::text),
    ('C9'::text, 'RUS'::text, 'Cirrus Airlines'::text),
    ('DO'::text, 'DOA'::text, 'Dominicana de Aviaci'::text),
    ('E3'::text, 'DMO'::text, 'Domodedovo Airlines'::text),
    ('KA'::text, 'HDA'::text, 'Dragonair'::text),
    ('EO'::text, 'LHN'::text, 'Express One International'::text),
    ('B5'::text, 'FLT'::text, 'Flightline'::text),
    ('TE'::text, 'LIL'::text, 'FlyLal'::text),
    ('EG'::text, 'JAA'::text, 'Japan Asia Airways'::text),
    ('7B'::text, 'KJC'::text, 'Krasnojarsky Airlines'::text),
    ('4M'::text, 'DSM'::text, 'LAN Argentina'::text),
    ('MJ'::text, 'LPR'::text, 'L'::text),
    ('MA'::text, 'MAH'::text, 'Malév'::text),
    ('JI'::text, 'MDW'::text, 'Midway Airlines'::text),
    ('NW'::text, 'NWA'::text, 'Northwest Airlines'::text),
    ('O8'::text, 'OHK'::text, 'Oasis Hong Kong Airlines'::text),
    ('RD'::text, 'RYN'::text, 'Ryan International Airlines'::text),
    ('NL'::text, 'SAI'::text, 'Shaheen Air International'::text),
    ('FT'::text, 'SRH'::text, 'Siem Reap Airways'::text),
    ('5G'::text, 'SSV'::text, 'Skyservice Airlines'::text),
    ('A4'::text, 'SWD'::text, 'Southern Winds Airlines'::text),
    ('NE'::text, 'ESK'::text, 'SkyEurope'::text),
    ('JK'::text, 'JKK'::text, 'Spanair'::text),
    ('JZ'::text, 'SKX'::text, 'Skyways Express'::text),
    ('NB'::text, 'SNB'::text, 'Sterling Airlines'::text),
    ('GE'::text, 'TNA'::text, 'TransAsia Airways'::text),
    ('LC'::text, 'VLO'::text, 'Varig Log'::text),
    ('VP'::text, 'VSP'::text, 'VASP'::text),
    ('VG'::text, 'VLM'::text, 'VLM Airlines'::text),
    ('Z4'::text, 'OOM'::text, 'Zoom Airlines'::text),
    (NULL::text, 'VOO'::text, 'Volotea'::text),
    (NULL::text, 'GFA'::text, 'Gulf Air'::text),
    ('TZ'::text, 'SCO'::text, 'Scoot'::text),
    ('HR'::text, 'CUA'::text, 'China United Airlines'::text),
    (NULL::text, 'LTD'::text, 'Southern Airways Express'::text),
    (NULL::text, 'ENY'::text, 'Envoy Air'::text),
    (NULL::text, 'QQQ'::text, 'ENTERair'::text),
    (NULL::text, NULL::text, 'Wataniya Airways'::text),
    ('UG'::text, 'TUI'::text, 'Tuninter'::text),
    ('JF'::text, 'JAF'::text, 'Jetairfly'::text),
    ('OI'::text, 'ORC'::text, 'Orchid Airlines'::text),
    ('CF'::text, 'SDR'::text, 'City Airline'::text)
    ) AS d(iata, icao, name)
   WHERE a.iata IS NOT DISTINCT FROM d.iata AND a.icao IS NOT DISTINCT FROM d.icao AND a.name = d.name AND a."isActive";
END $$;
