// Generates prisma/migrations/20261005000100_airline_reference_refresh/migration.sql from
// airlines-curated.json, so the SQL that corrects an EXISTING database and the JSON that seeds a NEW one can
// never disagree (src/lib/__tests__/airline-reference-data.test.ts checks both).
//
//   npx tsx prisma/seed-data/generate-airline-migration.ts
import fs from "node:fs";
import path from "node:path";
import { loadCuratedAirlines } from "./curated-airlines";

const MIGRATION = "20261005000100_airline_reference_refresh";

const text = (v: string | null | undefined) => (v == null ? "NULL::text" : `'${v.replace(/'/g, "''")}'::text`);
const bool = (v: boolean) => (v ? "true" : "false");

function main() {
  const file = loadCuratedAirlines();

  const curatedRows = file.airlines
    .map(
      (e) =>
        `    (${text(e.iata)}, ${text(e.icao)}, ${text(e.name)}, ${text(e.country)}, ${bool(e.isActive)}, ${text(e.mode)}, ${bool(!!e.keepPrevious)}, ${text(e.own?.name)}, ${text(e.own?.icao)}, ${text(e.own?.iata)})`
    )
    .join(",\n");
  const deactivateRows = file.deactivate.map((d) => `    (${text(d.iata)}, ${text(d.icao)}, ${text(d.name)})`).join(",\n");

  const sql = `-- Airline reference-data refresh (generated by prisma/seed-data/generate-airline-migration.ts from
-- prisma/seed-data/airlines-curated.json — edit that file and regenerate, never this one).
--
-- WHY: the bundled OpenFlights airline data is years old. Many airlines that operate today could not be found because
-- their IATA code was still held by a defunct airline that was later given the code again (Pegasus PC, Volotea V7,
-- SpiceJet SG, Jazeera J9, Starlux JX, Air Premia YP, Azul AD, Viva Aerobus VB, VietJet VJ ...), and ~75 carriers that
-- ceased long ago were still flagged active. Every entry below carries an IATA + ICAO pair that was cross-checked
-- against two independent sources (see the JSON).
--
-- SAFETY: nothing is deleted and no foreign key is touched. A recycled code is FREED from its previous holder, which keeps
-- its row, id, name and ICAO (marked inactive), so every existing FlightSegment still points at the airline it was saved
-- with. Where the holder is the same company renamed (Brussels Airlines, Norwegian, Envoy, Endeavor ...) the row is
-- relabelled in place. The script is idempotent (a second run changes nothing) and each airline is applied in its own
-- sub-transaction, so one unexpected row can never abort the rest or block a deploy.

DO $$
DECLARE
  r RECORD;
  h RECORD;
  own_id integer;
BEGIN
  -- 1. Placeholder IATA values in the old data ('--', '??', '8z', ...) are not designators: clear them.
  FOR r IN SELECT id FROM "Airline" WHERE iata IS NOT NULL AND iata !~ '^[A-Z0-9]{2}$' LOOP
    BEGIN
      UPDATE "Airline" SET iata = NULL WHERE id = r.id;
    EXCEPTION WHEN unique_violation THEN
      UPDATE "Airline" SET iata = NULL, icao = NULL WHERE id = r.id;
    END;
  END LOOP;

  -- 1b. Likewise ICAO values that are not three letters (placeholders such as 'BA1', '000'): clear them.
  UPDATE "Airline" SET icao = NULL WHERE icao IS NOT NULL AND icao !~ '^[A-Z]{3}$';

  -- 2. Curated corrections and additions.
  FOR r IN SELECT * FROM (VALUES
${curatedRows}
  ) AS t(iata, icao, name, country, is_active, mode, keep_previous, own_name, own_icao, own_iata)
  LOOP
    BEGIN
      SELECT id, name, icao, country INTO h FROM "Airline" WHERE iata = r.iata;

      -- The row holding this IATA already is this airline.
      IF h.id IS NOT NULL AND h.icao IS NOT DISTINCT FROM r.icao THEN
        UPDATE "Airline" SET name = r.name, "isActive" = r.is_active, country = COALESCE(country, r.country) WHERE id = h.id;
        CONTINUE;
      END IF;

      -- Same company renamed / successor on the same code: relabel in place, keep the previous identity if it differs.
      IF r.mode = 'relabel' AND h.id IS NOT NULL THEN
        IF r.keep_previous AND h.icao IS NOT NULL THEN
          INSERT INTO "Airline" (iata, icao, name, country, "isActive") VALUES (NULL, h.icao, h.name, h.country, false) ON CONFLICT DO NOTHING;
        END IF;
        UPDATE "Airline" SET name = r.name, icao = r.icao, "isActive" = r.is_active, country = COALESCE(country, r.country) WHERE id = h.id;
        CONTINUE;
      END IF;

      -- Recycled code: free it from the previous holder (kept as an inactive, code-less record).
      IF h.id IS NOT NULL THEN
        BEGIN
          UPDATE "Airline" SET iata = NULL, "isActive" = false, "logoUrl" = NULL WHERE id = h.id;
        EXCEPTION WHEN unique_violation THEN
          UPDATE "Airline" SET iata = NULL, icao = NULL, "isActive" = false, "logoUrl" = NULL WHERE id = h.id;
        END;
      END IF;

      -- The airline's own existing row (listed without, or under a wrong, IATA code) gains the code; otherwise add it.
      own_id := NULL;
      IF r.own_name IS NOT NULL THEN
        SELECT id INTO own_id FROM "Airline"
         WHERE name = r.own_name AND icao IS NOT DISTINCT FROM r.own_icao AND (iata IS NULL OR iata IS NOT DISTINCT FROM r.own_iata)
         ORDER BY id LIMIT 1;
      END IF;
      IF own_id IS NOT NULL THEN
        UPDATE "Airline" SET iata = r.iata, icao = r.icao, name = r.name, country = COALESCE(country, r.country), "isActive" = r.is_active, "logoUrl" = NULL WHERE id = own_id;
      ELSE
        INSERT INTO "Airline" (iata, icao, name, country, "isActive") VALUES (r.iata, r.icao, r.name, r.country, r.is_active) ON CONFLICT DO NOTHING;
      END IF;
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'airline refresh skipped % (%): %', r.iata, r.name, SQLERRM;
    END;
  END LOOP;

  -- 3. Airlines that ceased operating but were still flagged active. Only the flag changes — never a delete.
  UPDATE "Airline" a SET "isActive" = false
    FROM (VALUES
${deactivateRows}
    ) AS d(iata, icao, name)
   WHERE a.iata IS NOT DISTINCT FROM d.iata AND a.icao IS NOT DISTINCT FROM d.icao AND a.name = d.name AND a."isActive";
END $$;
`;

  const dir = path.join(__dirname, "..", "migrations", MIGRATION);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "migration.sql"), sql, "utf-8");
  console.log(`Wrote ${path.join(dir, "migration.sql")} (${file.airlines.length} curated, ${file.deactivate.length} deactivations)`);
}


main();
